### PR TITLE
chore: use consistent CE type values

### PR DESCRIPTION
**Pull request by zroubalik**
UPDATED: Let's use `.` in the CE type values

Signed-off-by: Zbynek Roubalik <zroubali@redhat.com>

### CODE REVIEW

**Comment by lance** [comment]
@zroubalik in the recommendations for CloudEvent type attribute, `.` is consistently used. I was thinking the other day that we should probably change all of the current `:` to `.`. I know that's a lot more files to touch, but wdyt?

**Comment by zroubalik** [comment]
@lance ok 😄 

That's the reason why I used `.` before, but I thought that the new convention is `:` brought by you, since you are more familiar with CE :)

I am ok, with doing the replacement to `.` for all files, I can modify this PR.

**Comment by lance** [comment]
> That's the reason why I used . before, but I thought that the new convention is : brought by you, since you are more familiar with CE :)

You busted me! Yes, I did introduce it - and I was incorrect! :laughing:

**Comment by zroubalik** [comment]
@lance updated, PTAL

**Review by lance — APPROVED** [review]

**Pull request merged**
