### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by matejvasek**
Signed-off-by: Matej Vasek <mvasek@redhat.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
@zroubalik refactor of `Output` type

**Comment by matejvasek** [comment]
NOTE: I haven't tested this in cluster yet.

**Review by lance — APPROVED** [review]
Nice improvements. What is still in progress/

**Comment by matejvasek** [comment]
I just tested this with mocked events on cluster (I don't have bot set up). Seems work.

**Comment by matejvasek** [comment]
@zroubalik PTAL and please test this

**Review by zroubalik — APPROVED** [review]
LGTM, thanks @matejvasek for the quick refactor. I can confirm that it is working as expected :)

**Pull request merged**
